ALTER TYPE position_type ADD VALUE IF NOT EXISTS 'DATA_ENGINEER';
ALTER TYPE position_type ADD VALUE IF NOT EXISTS 'DEVOPS';
ALTER TYPE position_type ADD VALUE IF NOT EXISTS 'ML_AI';
ALTER TYPE position_type ADD VALUE IF NOT EXISTS 'MOBILE';
ALTER TYPE position_type ADD VALUE IF NOT EXISTS 'QA';
ALTER TYPE position_type ADD VALUE IF NOT EXISTS 'SECURITY';
